version: "3.8"

services:
  backend:
    build: .
    container_name: news-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/newsdb
    depends_on:
      - mongo
    volumes:
      - .:/app
    networks:
      - news-network

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - news-network

volumes:
  mongo-data:

networks:
  news-network:
    driver: bridge
