apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-backend
  labels:
    app: news-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: news-backend
  template:
    metadata:
      labels:
        app: news-backend
    spec:
      containers:
        - name: backend
          image: your-dockerhub-username/news-backend:latest  # 🛑 Change this to your DockerHub image
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb://news-mongo:27017/newsdb"
---
apiVersion: v1
kind: Service
metadata:
  name: news-backend-service
spec:
  selector:
    app: news-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-mongo
  labels:
    app: news-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-mongo
  template:
    metadata:
      labels:
        app: news-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-storage
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: news-mongo
spec:
  selector:
    app: news-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
